
/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                              keymap.h
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                            Forrest Yu, January, 2004
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

/********************************************************************/
/*    "scan code" <--> "key" map.                                     */
/*    It should be and can only be included by keyboard.c!          */
/*	needs	include/keyboard.h
		include/type.h
		include/const.h*/
/********************************************************************/
#include"const.h"
#include"type.h"
#include"keyboard_type.h"

/* Keymap for US MF-2 keyboard. */

PUBLIC t_32 keymap[NR_SCAN_CODES * MAP_COLS] = {

/* scan-code			!Shift		Shift		E0 XX		*/
/* ==================================================================== */
/* 0x00 - none		*/	0,		0,		0,						RELEASED,
/* 0x01 - ESC		*/	ESC,		ESC,		0,					RELEASED,
/* 0x02 - '1'		*/	'1',		'!',		0,					RELEASED,
/* 0x03 - '2'		*/	'2',		'@',		0,					RELEASED,
/* 0x04 - '3'		*/	'3',		'#',		0,					RELEASED,
/* 0x05 - '4'		*/	'4',		'$',		0,					RELEASED,
/* 0x06 - '5'		*/	'5',		'%',		0,					RELEASED,
/* 0x07 - '6'		*/	'6',		'^',		0,					RELEASED,
/* 0x08 - '7'		*/	'7',		'&',		0,					RELEASED,
/* 0x09 - '8'		*/	'8',		'*',		0,					RELEASED,
/* 0x0A - '9'		*/	'9',		'(',		0,					RELEASED,
/* 0x0B - '0'		*/	'0',		')',		0,					RELEASED,
/* 0x0C - '-'		*/	'-',		'_',		0,					RELEASED,
/* 0x0D - '='		*/	'=',		'+',		0,					RELEASED,
/* 0x0E - BS		*/	BACKSPACE,	BACKSPACE,	0,	RELEASED,
/* 0x0F - TAB		*/	TAB,		TAB,		0,					RELEASED,
/* 0x10 - 'q'		*/	'q',		'Q',		0,					RELEASED,
/* 0x11 - 'w'		*/	'w',		'W',		0,					RELEASED,
/* 0x12 - 'e'		*/	'e',		'E',		0,					RELEASED,
/* 0x13 - 'r'		*/	'r',		'R',		0,					RELEASED,
/* 0x14 - 't'		*/	't',		'T',		0,					RELEASED,
/* 0x15 - 'y'		*/	'y',		'Y',		0,					RELEASED,
/* 0x16 - 'u'		*/	'u',		'U',		0,					RELEASED,
/* 0x17 - 'i'		*/	'i',		'I',		0,					RELEASED,
/* 0x18 - 'o'		*/	'o',		'O',		0,					RELEASED,
/* 0x19 - 'p'		*/	'p',		'P',		0,					RELEASED,
/* 0x1A - '['		*/	'[',		'{',		0,					RELEASED,
/* 0x1B - ']'		*/	']',		'}',		0,					RELEASED,
/* 0x1C - CR/LF		*/	ENTER,		ENTER,		PAD_ENTER,	RELEASED,
/* 0x1D - l. Ctrl	*/	CTRL_L,		CTRL_L,		CTRL_R,			RELEASED,
/* 0x1E - 'a'		*/	'a',		'A',		0,					RELEASED,
/* 0x1F - 's'		*/	's',		'S',		0,					RELEASED,
/* 0x20 - 'd'		*/	'd',		'D',		0,					RELEASED,
/* 0x21 - 'f'		*/	'f',		'F',		0,					RELEASED,
/* 0x22 - 'g'		*/	'g',		'G',		0,					RELEASED,
/* 0x23 - 'h'		*/	'h',		'H',		0,					RELEASED,
/* 0x24 - 'j'		*/	'j',		'J',		0,					RELEASED,
/* 0x25 - 'k'		*/	'k',		'K',		0,					RELEASED,
/* 0x26 - 'l'		*/	'l',		'L',		0,					RELEASED,
/* 0x27 - ';'		*/	';',		':',		0,					RELEASED,
/* 0x28 - '\''		*/	'\'',		'"',		0,				RELEASED,
/* 0x29 - '`'		*/	'`',		'~',		0,					RELEASED,
/* 0x2A - l. SHIFT	*/	SHIFT_L,	SHIFT_L,	0,	RELEASED,
/* 0x2B - '\'		*/	'\\',		'|',		0,					RELEASED,
/* 0x2C - 'z'		*/	'z',		'Z',		0,					RELEASED,
/* 0x2D - 'x'		*/	'x',		'X',		0,					RELEASED,
/* 0x2E - 'c'		*/	'c',		'C',		0,					RELEASED,
/* 0x2F - 'v'		*/	'v',		'V',		0,					RELEASED,
/* 0x30 - 'b'		*/	'b',		'B',		0,					RELEASED,
/* 0x31 - 'n'		*/	'n',		'N',		0,					RELEASED,
/* 0x32 - 'm'		*/	'm',		'M',		0,					RELEASED,	
/* 0x33 - ','		*/	',',		'<',		0,					RELEASED,
/* 0x34 - '.'		*/	'.',		'>',		0,					RELEASED,
/* 0x35 - '/'		*/	'/',		'?',		PAD_SLASH,	RELEASED,
/* 0x36 - r. SHIFT	*/	SHIFT_R,	SHIFT_R,	0,	RELEASED,
/* 0x37 - '*'		*/	'*',		'*',    	0,				RELEASED,
/* 0x38 - ALT		*/	ALT_L,		ALT_L,  	ALT_R,	RELEASED,
/* 0x39 - ' '		*/	' ',		' ',		0,					RELEASED,
/* 0x3A - CapsLock	*/	CAPS_LOCK,	CAPS_LOCK,	0,	RELEASED,
/* 0x3B - F1		*/	F1,		F1,		0,							RELEASED,
/* 0x3C - F2		*/	F2,		F2,		0,							RELEASED,
/* 0x3D - F3		*/	F3,		F3,		0,							RELEASED,
/* 0x3E - F4		*/	F4,		F4,		0,							RELEASED,
/* 0x3F - F5		*/	F5,		F5,		0,							RELEASED,
/* 0x40 - F6		*/	F6,		F6,		0,							RELEASED,
/* 0x41 - F7		*/	F7,		F7,		0,							RELEASED,
/* 0x42 - F8		*/	F8,		F8,		0,							RELEASED,
/* 0x43 - F9		*/	F9,		F9,		0,							RELEASED,
/* 0x44 - F10		*/	F10,		F10,		0,					RELEASED,
/* 0x45 - NumLock	*/	NUM_LOCK,	NUM_LOCK,	0,		RELEASED,
/* 0x46 - ScrLock	*/	SCROLL_LOCK,	SCROLL_LOCK,	0,	RELEASED,
/* 0x47 - Home		*/	PAD_HOME,	'7',		HOME,		RELEASED,
/* 0x48 - CurUp		*/	PAD_UP,		'8',		UP,			RELEASED,
/* 0x49 - PgUp		*/	PAD_PAGEUP,	'9',		PAGEUP,	RELEASED,
/* 0x4A - '-'		*/	PAD_MINUS,	'-',		0,			RELEASED,
/* 0x4B - Left		*/	PAD_LEFT,	'4',		LEFT,		RELEASED,
/* 0x4C - MID		*/	PAD_MID,	'5',		0,				RELEASED,
/* 0x4D - Right		*/	PAD_RIGHT,	'6',		RIGHT,	RELEASED,
/* 0x4E - '+'		*/	PAD_PLUS,	'+',		0,				RELEASED,
/* 0x4F - End		*/	PAD_END,	'1',		END,			RELEASED,
/* 0x50 - Down		*/	PAD_DOWN,	'2',		DOWN,		RELEASED,
/* 0x51 - PgDown	*/	PAD_PAGEDOWN,	'3',		PAGEDOWN,	RELEASED,
/* 0x52 - Insert	*/	PAD_INS,	'0',		INSERT,	RELEASED,
/* 0x53 - Delete	*/	PAD_DOT,	'.',		DELETE,	RELEASED,
/* 0x54 - Enter		*/	0,		0,		0,						RELEASED,
/* 0x55 - ???		*/	0,		0,		0,							RELEASED,
/* 0x56 - ???		*/	0,		0,		0,							RELEASED,
/* 0x57 - F11		*/	F11,		F11,		0,					RELEASED,
/* 0x58 - F12		*/	F12,		F12,		0,					RELEASED,
/* 0x59 - ???		*/	0,		0,		0,			RELEASED,
/* 0x5A - ???		*/	0,		0,		0,			RELEASED,
/* 0x5B - ???		*/	0,		0,		GUI_L,	RELEASED,
/* 0x5C - ???		*/	0,		0,		GUI_R,	RELEASED,
/* 0x5D - ???		*/	0,		0,		APPS,		RELEASED,
/* 0x5E - ???		*/	0,		0,		0,	RELEASED,
/* 0x5F - ???		*/	0,		0,		0,	RELEASED,
/* 0x60 - ???		*/	0,		0,		0,RELEASED,
/* 0x61 - ???		*/	0,		0,		0,	RELEASED,
/* 0x62 - ???		*/	0,		0,		0,	RELEASED,
/* 0x63 - ???		*/	0,		0,		0,	RELEASED,
/* 0x64 - ???		*/	0,		0,		0,	RELEASED,
/* 0x65 - ???		*/	0,		0,		0,	RELEASED,
/* 0x66 - ???		*/	0,		0,		0,	RELEASED,
/* 0x67 - ???		*/	0,		0,		0,	RELEASED,
/* 0x68 - ???		*/	0,		0,		0,	RELEASED,
/* 0x69 - ???		*/	0,		0,		0,	RELEASED,
/* 0x6A - ???		*/	0,		0,		0,	RELEASED,
/* 0x6B - ???		*/	0,		0,		0,	RELEASED,
/* 0x6C - ???		*/	0,		0,		0,	RELEASED,
/* 0x6D - ???		*/	0,		0,		0,	RELEASED,
/* 0x6E - ???		*/	0,		0,		0,	RELEASED,
/* 0x6F - ???		*/	0,		0,		0,	RELEASED,
/* 0x70 - ???		*/	0,		0,		0,	RELEASED,
/* 0x71 - ???		*/	0,		0,		0,	RELEASED,
/* 0x72 - ???		*/	0,		0,		0,	RELEASED,
/* 0x73 - ???		*/	0,		0,		0,	RELEASED,
/* 0x74 - ???		*/	0,		0,		0,	RELEASED,
/* 0x75 - ???		*/	0,		0,		0,	RELEASED,
/* 0x76 - ???		*/	0,		0,		0,	RELEASED,
/* 0x77 - ???		*/	0,		0,		0,	RELEASED,
/* 0x78 - ???		*/	0,		0,		0,	RELEASED,
/* 0x78 - ???		*/	0,		0,		0,	RELEASED,
/* 0x7A - ???		*/	0,		0,		0,	RELEASED,
/* 0x7B - ???		*/	0,		0,		0,	RELEASED,
/* 0x7C - ???		*/	0,		0,		0,	RELEASED,
/* 0x7D - ???		*/	0,		0,		0,	RELEASED,
/* 0x7E - ???		*/	0,		0,		0,	RELEASED,
/* 0x7F - ???		*/	0,		0,		0,	RELEASED,
};


